### ISSUE TITLE
Remove page when ShowInSearch is changed to false

### ISSUE THREAD

**Issue by matt-in-a-hat** [wilr/silverstripe-algolia#15]
Currently if a page was indexed and then you change it to `ShowInSearch=0` then it will not be removed and just retain the old version of that page in the index.

How do you think this might be possible to fix?

Something like this on `AlgoliaObjectExtension`?
```php
public function onBeforeWrite()
{
  // Item was already indexed but is changing to no longer be
  if ($this->owner->AlgoliaIndexed && $this->owner->ID && $this->owner->fieldChanged('ShowInSearch') && !$this->canIndexInAlgolia()) {
    $this->removeFromAlgolia();
  }
}
```

**Comment by wilr** [comment]
Yep to the above, though only comments 

1) removeFromAlgolia should just return false if it doesn't exist in Algolia so I wouldn't bother checking ShowInSearch field.

2) I'd put that in the existing onAfterPublish since take the case you have a searchable published page in Algolia, make it ShowInSearch = 0, only save draft then technically the published page should still be in Algolia.

**Comment by matt-in-a-hat** [comment]
> removeFromAlgolia should just return false if it doesn't exist in Algolia

It'd be useful if it did, but there's currently no check for this.

In fact, I'm not sure it's currently possible to check this without sending a query to Algolia. Even the `AlgoliaIndexed` is always set to a date even if it was removed.

Should we instead update this to set `AlgoliaIndexed` to null when it is deleted from the index, and update `removeFromAlgolia` to skip/return false if `AlgoliaIndexed` is null (i.e. it shouldn't be indexed already so shouldn't need to remove)?

That way we can do as you say and just call this in `onAfterPublish` like
```php
if (min($this->owner->invokeWithExtensions('canIndexInAlgolia')) == false) {
    $this->owner->removeFromAlgolia();
} else {
    $this->owner->indexInAlgolia();
}
```

Otherwise currently I don't want to run a remove call every time the page is published.
