### ISSUE TITLE
Heads up: documentation does not match release 0.1.0

### ISSUE THREAD

**Issue by brynnb** [wilr/silverstripe-algolia#18]
Just had a long bout of troubleshooting why my algolia application ID was not pulling in as it should from the .yaml file, and it turns out composer was pulling in version 0.1.0 rather than the latest commit.  Changing the version to `dev-master#39af51113de150fe9c67e3949a631a3b565ac5df` and running `composer update` fixed the issue though. It seems there has been some change in how it pulls in configuration values. Just posting this in case it helps someone else.

Thanks for the great module!

**Comment by wilr** [comment]
I've tagged a 0.2.0 with the latest changes. Sorry for the confusion!

**Comment by brynnb** [comment]
Thanks wilr!
