### ISSUE TITLE
objectSilverstripeUUID in one place and objectSilverstripeID in another

### ISSUE THREAD

**Issue by brynnb** [wilr/silverstripe-algolia#23]
https://github.com/wilr/silverstripe-algolia/blob/master/src/Service/AlgoliaQuerier.php#L34

https://github.com/wilr/silverstripe-algolia/blob/master/src/Service/AlgoliaIndexer.php#L114

The indexer is setting the attribute to `objectSilverstripeID` but the Querier is looking for `objectSilverstripeUUID`. This leads to it not returning any results. Not sure which is the intended name or what other ramifications might happen from changes, otherwise I'd submit a PR.

Thanks again @wilr

**Comment by brynnb** [comment]
And to clarify, setting it to `objectSilverstripeID` in the Quirier makes things work as expected.

**Comment by wilr** [comment]
Ah ok sorry - yes I think `objectSilverstripeUUID` is clearer that it has nothing to do with an `ID`
