### ISSUE TITLE
Running Reindex only seems to index half of the available pages per run

### ISSUE THREAD

**Issue by brynnb** [wilr/silverstripe-algolia#24]
For example, on the first run it will output:

`Found 4646 pages remaining to index, will export in batches of 20, grouped by type.`

and show progress such as ` [50/4646]` and end when it hits ` [2300/4646]`

Looking in the database, only about 2323 records got indexed (half).

If you run it again, it outputs:

`Found 2336 pages remaining to index, will export in batches of 20, grouped by type.`

I have to repeat the command several times until it finally halves down to the last 50 or so, and then it will finish those last 50 just fine. 

Not a breaking bug and unfortunately don't have time to dive in more and propose a fix, but wanted to post it here in case it was easily replicated/fixed or anyone else runs into it.

**Comment by wilr** [comment]
Can you re-try on 0.3.0 and let me know how you get on? I get all 1700 pages done in 1 hit.
