### ISSUE TITLE
AlgoliaReindex command only indexes SiteTree by default even when includeClasses yml has others

### ISSUE THREAD

**Issue by brynnb** [wilr/silverstripe-algolia#25]
Not a big deal, but expected behavior would be for the AlgoliaReindex command to index everything under includeClasses in the yml. Right now I have to explicitly add a flag and run a separate command for each class.

Not complaining - just trying to help by documenting feature enhancements. Thanks wilr!

**Comment by wilr** [comment]
Fixed in `0.3.0`
