### ISSUE TITLE
Handling of content blocks and document text indexing

### ISSUE THREAD

**Issue by camfindlay** [wilr/silverstripe-algolia#30]
Does this addon deal with the content block model of content (elemental et al.) and the option to fulltext index documents?

**Comment by wilr** [comment]
@camfindlay yes - it indexes the content as per rendered in the template so captures anything you put in the `main` HTML element (https://github.com/wilr/silverstripe-algolia/blob/master/src/Service/AlgoliaPageCrawler.php)

**Comment by camfindlay** [comment]
Nice! Thanks @wilr - and how about indexing other docs? Would you still need some other text extraction method (Using Tika or similar).

**Comment by wilr** [comment]
Yes this module doesn't do any fulltext extraction of documentation such as PDFs etc. Algolia recommends Tika as well (https://stories.algolia.com/indexing-pdf-or-other-file-contents-for-searching-b2499c23568f)

**Comment by camfindlay** [comment]
@wilr can you give me more info about how the crawler works for elemental? Have been attempting to get running but so far hasn't picked up page content from a configured alternative Xpath location. Should `Wilr\SilverStripe\Algolia\Service\AlgoliaPageCrawler:` be configed in the Injector in the YAML?

**Comment by matt-in-a-hat** [comment]
As a side note, I indexed elemental content without the Page Crawler by doing something roughly like below
```yml
Wilr\SilverStripe\Algolia\Service\AlgoliaIndexer:
  include_page_content: false
```

Page.php
```php
    public function updateAlgoliaAttributes(&$attributes)
    {
        // Algolia has per-record size limits, so ensure we don't go over
        $text = $this->getTextContentForSearchIndex();
        $CHAR_LIMIT = 8000;
        if (mb_strlen($text) > $CHAR_LIMIT) {
            $text = mb_substr($text, 0, $CHAR_LIMIT);
        }
        $attributes->push('objectTextContent', $text);
         // include other attrs like previewImage etc
    }

    // Child classes of Page override this a prepend any special content
    public function getTextContentForSearchIndex()
    {
        $text = $this->Summary . ' ';
        foreach ($this->ElementalArea()->Elements() as $element) {
            $searchContent = $element->invokeWithExtensions('onBeforeSearchIndexing');
            if ($searchContent) {
                $text .= implode(' ', $searchContent) . ' ';
            }
        }
        return $text;
    }
```

There's probably a better way of handling the record size limits too. I can't remember exactly but I think Algolia was just refusing to index records that were too large, so were either breaking or silently failing the index job.

**Comment by wilr** [comment]
@matt-in-a-hat This should be handled already by the block extractor - https://github.com/wilr/silverstripe-algolia/blob/master/src/Service/AlgoliaIndexer.php#L164-L189 you can set a maximum size of each block to fit within the limits of your plan.

**Comment by matt-in-a-hat** [comment]
Isn't that for fields on the page itself? ElementalArea is a relation, so would perhaps just end up [calling `updateAlgoliaRelationshipAttributes` on it](https://github.com/wilr/silverstripe-algolia/blob/8c92bd56c8f5dc9cb0f9b2fd79819c4d16b6db0b/src/Service/AlgoliaIndexer.php#L215)?

**Comment by thats4shaw** [comment]
I haven't had much luck getting it working with Elemental out of box with neither the standard main element setup or a custom xpath selector.

Looking into @matt-in-a-hat's suggestion.

**Comment by thats4shaw** [comment]
Just getting back to this.

I'm finding that the AlgoliaPageCrawler is rendering content using the following template vendor/silverstripe/framework/templates/SilverStripe/Control/Controller.ss which is pretty interesting.

**Comment by wilr** [comment]
@thats4shaw It shouldn't be using that unless there isn't a matching template for your block - that's the fallback.

**Comment by thats4shaw** [comment]
Can confirm it's got a matching template - the front end of the site is working.

**Comment by thats4shaw** [comment]
Ironically i've struck this problem before in a different context - https://github.com/silverstripe/silverstripe-elemental/issues/228.

Theme templates aren't in play in the context of the crawler.

Doing something like what's demonstrated at https://github.com/silverstripe/silverstripe-elemental/pull/262/files works around it.

**Comment by wilr** [comment]
@thats4shaw Thanks, I've tested and added something similar to in #37. I hadn't picked that up as all our sites don't bother with themes and just use `app/templates`

**Comment by thats4shaw** [comment]
Nice @wilr.  I was just about to put a PR through too!
