### ISSUE TITLE
Does this search addon support the "Show in search?" settings option?

### ISSUE THREAD

**Issue by camfindlay** [wilr/silverstripe-algolia#31]
On some testing my CMS throughs 500 errors once I have indexed and then attempt to change this setting in the settings. Ideally if we set `Show in search?` to false I'd like it to fire the same hook as unpublishing so that it doesn't show in results.

**Comment by wilr** [comment]
Yep it sure does - https://github.com/wilr/silverstripe-algolia/blob/master/src/Extensions/AlgoliaObjectExtension.php#L96-L109. When you publish your change to `ShowInSearch` it will either index or remove it.

**Comment by camfindlay** [comment]
Ok cheers, I'll test it further I figured it would but was getting errors in the case where we published a page that got indexed, then turned off the 'show in search' and pressed publish again. Will see if I can get more details from the error log.
