### ISSUE TITLE
Multi language support (fluent)

### ISSUE THREAD

**Issue by teundirectlease** [wilr/silverstripe-algolia#33]
It would be great to have an option for multi language support. Algolia supports multi languages in 2 ways:
1. every language has their own index
2. every language_field is in one object and you exclude the others.

I think option 1 is cleaner and it would be nice if you can add it ass a config prop in the yaml. You will get your agolia indexes for every environment and local:
{env}_{lndex_name}_{locale}

**Comment by wilr** [comment]
@teundirectlease happy to accept PR's for option 1. I think that's the easiest to manage.

**Comment by knirb** [comment]
I can maybe help with this. I have extended the module to be able to create separate indexes per subsite/locale combo. Would have to modify it a bit to be able to configure wether to use subsites or not, but will see what I can do.
