### ISSUE TITLE
exportObjectToAlgolia() method doesn't work as documented.

### ISSUE THREAD

**Issue by matthewrayner** [wilr/silverstripe-algolia#47]
The `exportObjectToAlgolia()` method call in `AlgoliaIndexer::exportAttributesFromObject` expects a `SilverStripe\ORM\Map`.

The documentation however refers to merging an array with `array_merge` and returning it.
This causes an error when it tries to call `toArray()` on the array in `AlgoliaIndexer::indexItems`.

This also appears to skip adding `objectForTemplate` to the index and other indexing options.

I suspect the documentation should refer to using using `updateAlgoliaAttributes()` instead...

```php
/**
 * @var SilverStripe\ORM\Map $attributes
 */
public function updateAlgoliaAttributes(&$attributes)
{
    $attributes->push('objectCustomThing', $this->MyCustomThingField);
}
```

**Comment by wilr** [comment]
@matthewrayner Make sure you're on the latest release, I believe this is already fixed.

updateAlgoliaAttributes is always passed a Map object. 
https://github.com/wilr/silverstripe-algolia/blob/main/src/Service/AlgoliaIndexer.php#L258
