### ISSUE TITLE
AlgoliaReindex task doesn't remove old records from the index

### ISSUE THREAD

**Issue by zaidaldabbagh** [wilr/silverstripe-algolia#55]
### Current Behaviour

The **AlgoliaReindex** task doesn't seem to remove existing records that no longer exists in SilverStripe ... For example, let's say Content Item X was removed, executing the AlgoliaReindex task doesn't seem to remove it from the Index even with the `forceAll=1` being passed. This is undesirable, as it means Algolia's InstantSearch will still present this no longer existing item in the hits.

The only solution would be to clear out the full index, and to do a full re-index, which unfortunately is quiet slow at the moment, and takes about 10 minutes, which would be distributive for users, as we have a cron job that re-indexes records every few hours throughout the day.

### Expected Behaviour

Ideally, when running the AlogoliaReindex task, old records that no longer exist in SilverStripe are removed from the index, so it no longer appears in the InstantSearch hits.

**Comment by wilr** [comment]
Hi @zaidaldabbagh You are correct, forceAll forces all records in Silverstripe to be re-indexed. It does not clear all existing ones. I've added a `clearAll` flag now.

**Comment by zaidaldabbagh** [comment]
@wilr do you have a new published version that we can install?

**Comment by wilr** [comment]
You can always use `dev-main#commit` for testing the change instantly. I've tagged `1.4.13` as well.
