### ISSUE TITLE
Indexing draft elemental content

### ISSUE THREAD

**Issue by josephlewisnz** [wilr/silverstripe-algolia#64]
Hi

I  am trying to manually index some pages.

In my scenario I have a published page but an elemental block (with some draft changes).

However when I trigger the `->indexInAlgolia();` my objectForTemplate prop is populated with draft content 

I am just currently trying to look into why this is occurring and if there is anything I can do to fix it.

I've even tried something like this to force. However I think this is actually occuring in the getMainContent() 
```
 $liveParentPage = Versioned::get_by_stage($projectPage->ClassName, Versioned::LIVE)->byID($projectPage->ID);

if (min($liveParentPage->invokeWithExtensions('canIndexInAlgolia')) == false) {
    $liveParentPage->removeFromAlgolia();
} else {
    $liveParentPage->indexInAlgolia();
}
```

**Comment by josephlewisnz** [comment]
I'm just doing some testing - but I may have an approach to fix this - it's not very elegant..

This seems like very impactful to the module so I would love to know your opinion or if you have a better solution @wilr 

Basically doing the old 
```
        $originalStage = Versioned::get_stage();
        Versioned::set_stage('Live');
        
        ... controller + render + html stuff
        
          Versioned::set_stage($originalStage);      
        
        
```

**Comment by josephlewisnz** [comment]
This is just a side note - but I just realised that the latest version is now only for framework 5.
https://github.com/wilr/silverstripe-algolia/compare/1.5.0...1.5.1

Should this have been a new major release? 

I'm just testing the possibility of having 
`"symbiote/silverstripe-queuedjobs": "^4 || ^5",`

**Comment by michalkleiner** [comment]
Removing support for SS4 should be a new major version.
Adding support for CMS5 while keeping support for CMS4 is usually a new minor version.
